### PR TITLE
bug: Normalize the address obtained from the DApp.

### LINKED ISSUE #47: bug: Retrieve the `doesn't match` error from the Background when swapping tokens in Uniswap.
Retrieve the `Address doesn't match connected account` error from the Background when swapping tokens in [Uniswap](https://app.uniswap.org/swap).

### PR DESCRIPTION
**Pull request by oneleo**
# bug: Normalize the address obtained from the DApp.

# doc: Added current results demo and reproduction process markdown

## Issue linked
- Resolves #47

## Issue description
1. For instance, the [Uniswap DApp](https://app.uniswap.org/swap) does not perform address normalization, resulting in persistent "doesn't match" errors.

### CODE REVIEW

File: packages/provider/waallet/background/provider.ts [hunk 1]
```diff
@@ -82,13 +82,16 @@ export class WaalletBackgroundProvider {
...
+      tx.from &&
+      ethers.getAddress(tx.from) !== (await this.account.getAddress())
+    ) {
       throw new Error("Address `from` doesn't match connected account")
     }
     // TODO: Use account's entry point
     const [entryPointAddress] = await this.bundler.getSupportedEntryPoints()
     const userOpCall = await this.account.createUserOperationCall({
-      to: tx.to,
+      to: ethers.getAddress(tx.to),
```
Comment (pilagod) [inline packages/provider/waallet/background/provider.ts:94]: Q: Is it required the conversion here?

Comment (pilagod) [reply packages/provider/waallet/background/provider.ts]: In longer view it would be better to have a class to denote the address value, just like #49. We can first think more about the question: is there any good place to do the conversion for us?

**Review by pilagod — APPROVED** [review]

File: packages/provider/waallet/background/provider.ts (hunk 1 above)
Comment (oneleo) [reply packages/provider/waallet/background/provider.ts]: OK! I just reviewed the content of #49.
It introduces a `UserOperation` class for seamless handling and offers a `data()` method, mainly converting `BigInt` to `Hex`.
Using classes helps centralize data processing. If conversion methods change in the future, modifying the class suffices for global adjustments.
For instance, we can add `EthEstimateGas` and `EthSendTransaction` classes for implicit address normalization.
